Repository SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway, pull requests merged in 2022-04, with the labels that each got.

#109 240: AISP evaluation script
  config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
  config/7.0/obdemo-bank/ig/scripts/groovy/TranslateAccountsResource.groovy
Labels: bug

#112 230: domestic payment patch consent
  config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Labels: bug, enhancement, IG

#113 Add Domestic Payments Consents APIs in the RS Discovery
  config/7.0/obdemo-bank/ig/scripts/groovy/ProcessRs.groovy
Labels: enhancement, IG

#115 Change the 'issuer' domain in WellKnownFilter.groovy
  config/7.0/obdemo-bank/ig/scripts/groovy/WellKnownFilter.groovy
Labels: bug, IG
