Repository SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway, pull requests merged in 2022-02, with the labels that each got.

#84 206: repo route environment map values fix
  README.md
  kustomize/overlay/7.0/obdemo-bank/andra-racovita/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/andra-racovita/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/bohocode/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/bohocode/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/christian-brindley/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/christian-brindley/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/defaults/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/defaults/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/dev/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/jorgesanchezperez/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/jorgesanchezperez/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/jterryfr/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/local/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/mariantiris/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/mariantiris/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/nightly/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/nightly/kustomization.yaml
Labels: bug, enhancement, IG

#91 Fix Jamie (BohoCode) environment, typo error
  kustomize/overlay/7.0/obdemo-bank/BohoCode/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/BohoCode/kustomization.yaml
Labels: bug, deployment

#95 Adding pattern to cover all patch versions
  config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json
  config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-balances-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/13-ob-account-transactions-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/14-ob-account-beneficiaries-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/15-ob-account-direct-debits-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/16-ob-account-standing-orders-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/17-ob-account-products-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/18-ob-account-offers-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/19-ob-account-party-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/20-ob-account-scheduled-payments-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/21-ob-account-statements-access.json
Labels: enhancement, IG
