Repository SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway, pull requests merged in 2022-03, with the labels that each got.

#98 204: indentity platform client libraries
  config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
  config/7.0/obdemo-bank/ig/routes/routes-service/60-internal-repo.json
  config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy
Labels: enhancement, deployment, IG

#99 Domestic payment consent
  config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json
  config/7.0/obdemo-bank/ig/routes/routes-service/30-ob-payment-consent.json
  config/7.0/obdemo-bank/ig/scripts/groovy/ProcessPaymentConsent.groovy
Labels: IG

#100 229: cdk and cdm platform with the same configuration
  .github/workflows/merge.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  README.md
  bin/config.sh
  config/7.0/obdemo-bank/ig/config/dev/config/config.json
  config/7.0/obdemo-bank/ig/config/prod/config/config.json
  config/7.0/obdemo-bank/ig/routes/routes-service/01-ob-rs-metadata.json
  config/7.0/obdemo-bank/ig/routes/routes-service/02-ob-as-metadata.json
  config/7.0/obdemo-bank/ig/routes/routes-service/03-ob-as-register.json
  config/7.0/obdemo-bank/ig/routes/routes-service/10-ob-account-consent.json
  config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
  config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
  config/7.0/obdemo-bank/ig/routes/routes-service/30-ob-payment-consent.json
  config/7.0/obdemo-bank/ig/routes/routes-service/31-ob-payment-submission.json
  config/7.0/obdemo-bank/ig/routes/routes-service/54-ob-token-endpoint.json
  config/7.0/obdemo-bank/ig/routes/routes-service/60-internal-repo.json
  config/7.0/obdemo-bank/ig/routes/routes-service/99-ob-as.json
  kustomize/base/7.0/ingress/ingress.yaml
  kustomize/base/kustomizeConfig/kustomization.yaml
  kustomize/base/obdemo-bank/application.yaml
  kustomize/overlay/7.0/obdemo-bank/andra-racovita/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/bohocode/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/christian-brindley/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/defaults/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/jorgesanchezperez/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/local/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/local/deployment-patch.yaml
  kustomize/overlay/7.0/obdemo-bank/local/ingress-patch.yaml
  kustomize/overlay/7.0/obdemo-bank/local/kustomization.yaml
  kustomize/overlay/7.0/obdemo-bank/mariantiris/configmap.yaml
  kustomize/overlay/7.0/obdemo-bank/nightly/configmap.yaml
Labels: enhancement, deployment

#106 17: account statement file check response error
  config/7.0/obdemo-bank/ig/scripts/groovy/ObResponseCheck.groovy
Labels: bug, enhancement

#108 236: register client, create consent
  config/7.0/obdemo-bank/ig/scripts/groovy/CreateApiClient.groovy
  config/7.0/obdemo-bank/ig/scripts/groovy/ObResponseCheck.groovy
Labels: bug, enhancement, deployment
